[package]
name = "run-in-thread"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
description = "Run actix-web in separate thread"

[dependencies]
ntex = "0.2.0-b.14"
env_logger = "0.8"
