[package]
name = "form-example"
version = "1.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.2.0-b.14"
serde = { version = "1.0", features = ["derive"] }
