[package]
name = "basics"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.2.0-b.14"
ntex-files = "0.1.0"
ntex-session = "0.1.0"
futures = "0.3.4"
env_logger = "0.7"
bytes = "0.5"
