[package]
name = "error_handling"
version = "1.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.2.0-b.14"
derive_more = "0.99.5"
futures = "0.3.4"
rand = "0.7"
env_logger = "0.7"
