[package]
authors = ["Dan Munckton <dangit@munckfish.net>"]
name = "todo"
version = "2.0.0"
edition = "2018"

[dependencies]
ntex = "0.2.0-b.14"
ntex-files = "0.1.0"
ntex-session = "0.1.0"
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3.4"
log = "0.4.3"
serde = { version = "1.0.69", features = ["derive"] }
serde_json = "1.0.22"
tera = "1.0"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "1.3.2"
