[package]
name = "websocket"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
ntex = "0.2.0-b.14"
ntex-files = "0.1.0"
env_logger = "0.7"
futures = "0.3.4"
bytes = "0.5.4"
